#!/bin/sh
### BEGIN INIT INFO
# Provides:          pi-wall 
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop:    
# Short-Description: Execute the reboot command.
# Description:
### END INIT INFO

DIR=/home/pi/pi-wall/src
DAEMON=$DIR/pi-wall.py
DAEMON_NAME=pi-wall

DAEMON_USER=pi

PIDFILE=/var/run/$DAEMON_NAME.pid

. /lib/lsb/init-functions

do_start () {
	log_daemon_msg "Starting $DAEMON_NAME daemon"
	start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --user $DAEMON_USER --chuid $DAEMON_USER --startas $DAEMON
	log_end_msg $?
}

do_stop () {
	log_daemon_msg "Stopping $DAEMON_NAME daemon"
	start-stop-daemon --stop --pidfile $PIDFILE --retry 10
	log_end_msg $?
}

case "$1" in

  start|stop)
	do_${1}
	;;

  restart|reload|force-reload)
	do_stop
	do_start
        ;;
  status)
	status_of_proc "$DAEMON_NAME" "$DAEMON" && exit 0 || exit $?
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 1
        ;;

esac
exit 0
